### ISSUE TITLE
Some webpages without dark theme

### ISSUE THREAD

**Issue by EstherMoellman** [ThomazPom/Moz-Ext-UltimaDark#1]
Hi @ThomazPom ,

Firstly, thank you for your add-on.
I'm a long time dark theme user, and I believe I've tested almost all darker add-ons. And your UltimaDark positively surprised me, not just because it works pretty well on most of the webpages, but also because its good performance (no white flash, no webpage breakages, good webpage loading and browser speed)... congrats for your good job.

I just found its RAM consume a little high (2.5MB), and also found some webpages where the dark theme is not working:
https://www.youtube.com/
https://userstyles.org/
https://edition.cnn.com/travel/article/first-flight-largest-electric-aircraft-scli-intl/index.html

Thank you again for your nice work.

**Comment by ThomazPom** [comment]
Yeah i know exactly why it does this, and i'm working on it very hard right now :)
