### ISSUE TITLE
Non Image edition Broken site(s)

### ISSUE THREAD

**Issue by chmichael** [ThomazPom/Moz-Ext-UltimaDark#102]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I am on a compatible (Desktop) browser that is up-to-date or explicitly listed as being compatible in the [README](https://www.github.com/ThomazPom/Moz-Ext-UltimaDark/blob/master/readme.md)
- [X] I'm reporting that UltimaDark is broken in a novel way that deserves it's own issue meaning it should not be added to [#6](https://www.github.com/ThomazPom/Moz-Ext-UltimaDark/issues/6) [#7](https://www.github.com/ThomazPom/Moz-Ext-UltimaDark/issues/7) [#8](https://www.github.com/ThomazPom/Moz-Ext-UltimaDark/issues/8) or [#94](https://www.github.com/ThomazPom/Moz-Ext-UltimaDark/issues/94)
- [X] This site is not listed in an existing issue or in [#6](https://www.github.com/ThomazPom/Moz-Ext-UltimaDark/issues/6) [#7](https://www.github.com/ThomazPom/Moz-Ext-UltimaDark/issues/7) [#8](https://www.github.com/ThomazPom/Moz-Ext-UltimaDark/issues/8) or [#94](https://www.github.com/ThomazPom/Moz-Ext-UltimaDark/issues/94)
- [X] I verified that I am on the latest version
- [X] I verified that ImageEdition, Caching, Service Worker Compatibility and the extension itself are all enabled and that I loaded the site cleanly by closing the tab and opening the URL in a new tab or I flushed it completely with [Tab Suspender](https://www.github.com/Hau-Hau/firefox-tab-suspender)
- [X] I tried disabling caching and refreshing the page several times and it is still broken.
- [X] I confirmed that the target site is not on the excluded sites list or a Mozilla domain on Firefox's protected site listin about:config
- [X] I've searched [known issues](https://www.github.com/ThomazPom/Moz-Ext-UltimaDark/issues) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [README](https://www.github.com/ThomazPom/Moz-Ext-UltimaDark/blob/master/readme.md) and understand how and why to open an issue.

### Site URL

With image edition Disabled

google.com search: "images". Either on the result or if you click the "Images" tab of the result the first images aren't shown.

### Provide a description of what about the site is broken and attach screenshots at the bottom

![εικόνα](https://github.com/user-attachments/assets/6d755d6d-22bc-422b-8e29-fa5bcfd66b19)

### Provide console logs

- [ ] Go to about:debugging#/runtime/this-firefox
- [ ] Click "Inspect" on UltimaDark
- [ ] Clear the log and refresh the page that is broken
- [ ] Copy the WHOLE output and insert it below

**Comment by ThomazPom** [comment]
Did i made a mistake breaking sites in 1.5.67?

**Comment by ThomazPom** [comment]
Wow yeah. Sorry for the mess.

**Comment by chmichael** [comment]
It's an old bug before 60 build which i forgot to report 😄

**Comment by ThomazPom** [comment]
Found and fixed in https://github.com/ThomazPom/Moz-Ext-UltimaDark/commit/9abc4febb5b51c88a918f545d3df2e8b1f784215
Google somehow managed to be faster than UltimaDark in page edition. I had to make the UltimaDark installation faster. There is still room an even faster UltimaDark installation, but it feels good enough for now.
Releasing 1.5.68 now on the store

**Comment by chmichael** [comment]
That was fast! I was hoping mozilla extensions updates to be so fast too. Can i install it manually ?

**Comment by chmichael** [comment]
That was fast! I'll reopen if i found anything related.
