### ISSUE TITLE
Ultimadark blocks Proton pass autofill freature

### ISSUE THREAD

**Issue by Max-109** [ThomazPom/Moz-Ext-UltimaDark#111]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I am on a compatible (Desktop) browser that is up-to-date or explicitly listed as being compatible in the [README](https://www.github.com/ThomazPom/Moz-Ext-UltimaDark/blob/master/readme.md)
- [X] I'm reporting that UltimaDark is broken in a novel way that deserves it's own issue meaning it should not be added to [#6](https://www.github.com/ThomazPom/Moz-Ext-UltimaDark/issues/6) [#7](https://www.github.com/ThomazPom/Moz-Ext-UltimaDark/issues/7) [#8](https://www.github.com/ThomazPom/Moz-Ext-UltimaDark/issues/8) or [#94](https://www.github.com/ThomazPom/Moz-Ext-UltimaDark/issues/94)
- [X] This site is not listed in an existing issue or in [#6](https://www.github.com/ThomazPom/Moz-Ext-UltimaDark/issues/6) [#7](https://www.github.com/ThomazPom/Moz-Ext-UltimaDark/issues/7) [#8](https://www.github.com/ThomazPom/Moz-Ext-UltimaDark/issues/8) or [#94](https://www.github.com/ThomazPom/Moz-Ext-UltimaDark/issues/94)
- [X] I verified that I am on the latest version
- [X] I verified that ImageEdition, Caching, Service Worker Compatibility and the extension itself are all enabled and that I loaded the site cleanly by closing the tab and opening the URL in a new tab or I flushed it completely with [Tab Suspender](https://www.github.com/Hau-Hau/firefox-tab-suspender)
- [X] I tried disabling caching and refreshing the page several times and it is still broken.
- [X] I confirmed that the target site is not on the excluded sites list or a Mozilla domain on Firefox's protected site listin about:config
- [X] I've searched [known issues](https://www.github.com/ThomazPom/Moz-Ext-UltimaDark/issues) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [README](https://www.github.com/ThomazPom/Moz-Ext-UltimaDark/blob/master/readme.md) and understand how and why to open an issue.

### Site URL

It does not work on every website

### Provide a description of what about the site is broken and attach screenshots at the bottom

Whenever i enable ultimarkdark then proton pass autofill stops working and if i disable ultimadark then it becomes available. Its really hard to see ultimadark cause this

### Provide console logs

- [ ] Go to about:debugging#/runtime/this-firefox
- [ ] Click "Inspect" on UltimaDark
- [ ] Clear the log and refresh the page that is broken
- [ ] Copy the WHOLE output and insert it below

**Comment by ThomazPom** [comment]
Thank you for reporting this issue with the new template 
https://github.com/ThomazPom/Moz-Ext-UltimaDark/issues/90

**Comment by ThomazPom** [comment]
I’m eager to understand why it does not work.

**Comment by Max-109** [comment]
> I’m eager to understand why it does not work.

Yeah i basically disable Ultimadark and it instantly (after reloading the page :) starts working

**Comment by Max-109** [comment]
And btw, is it supposed to be like this? (almost fully white picture) https://primordial.dev/
![image](https://github.com/user-attachments/assets/cdd524cf-2c9b-4825-ad3d-2f2f234319cc)
Without extension the image looks fine

**Comment by ThomazPom** [comment]
Here’s a polished version of your issue comment:

This seems to be an edge case related to the image editing feature, specifically the part designed to detect and brighten logos. It appears that the background image is being misclassified as a logo, which results in it being unnecessarily lightened.

Determining whether an image is or will be used as a background, a logo, or a photo given the performance contraints is indeed a very challenging task i don’t know how to solve since years. This is likely why similar issues exist across other image-editing-related features.

**Comment by Max-109** [comment]
hi, @ThomazPom !
Are there any news about this issue?

**Comment by ThomazPom** [comment]
This subject is not a priority and likely won’t be addressed for at least the next 30 days. There are currently more critical bugs to resolve, and I’m expecting the birth of my first child in just a few days.

**Comment by Max-109** [comment]
That's wonderful, congratulations!

**Comment by stripedew** [comment]
Just wanted to add that I'm experiencing the same issue - I used to have a similar issue with DarkReader, although it worked on 90% of websites and only a few didn't work, whereas here every page doesn't work. Trying to see if I can figure out a workaround while the dev is busy.
Hope all went well with the baby!

**Comment by ThomazPom** [comment]
Release v1.6.11
Resolved compatibility issues with other applications, including ProtonPass, by removing the coliding redefinition of shared `globalThis.exportFunction`  and having our own `uDark.exportFunction `definition.

https://github.com/ThomazPom/Moz-Ext-UltimaDark/releases/tag/v1.6.11

https://github.com/ThomazPom/Moz-Ext-UltimaDark/commit/0d040896b65a5b6e76c2b3057e6b44ae2f56febb#diff-673e98e9518fe407b7538bc62ef555f6eb5290996f4ea87b66783700af9a8a03R6

**Comment by stripedew** [comment]
Amazing, works a treat now @ThomazPom :)
This and #90 can be closed now
