### ISSUE TITLE
Quickbooks design completely broken

### ISSUE THREAD

**Issue by hunkyburrito** [ThomazPom/Moz-Ext-UltimaDark#118]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I am on a compatible (Desktop) browser that is up-to-date or explicitly listed as being compatible in the [README](https://www.github.com/ThomazPom/Moz-Ext-UltimaDark/blob/master/readme.md)
- [X] I'm reporting that UltimaDark is broken in a novel way that deserves it's own issue meaning it should not be added to [#6](https://www.github.com/ThomazPom/Moz-Ext-UltimaDark/issues/6) [#7](https://www.github.com/ThomazPom/Moz-Ext-UltimaDark/issues/7) [#8](https://www.github.com/ThomazPom/Moz-Ext-UltimaDark/issues/8) or [#94](https://www.github.com/ThomazPom/Moz-Ext-UltimaDark/issues/94)
- [X] This site is not listed in an existing issue or in [#6](https://www.github.com/ThomazPom/Moz-Ext-UltimaDark/issues/6) [#7](https://www.github.com/ThomazPom/Moz-Ext-UltimaDark/issues/7) [#8](https://www.github.com/ThomazPom/Moz-Ext-UltimaDark/issues/8) or [#94](https://www.github.com/ThomazPom/Moz-Ext-UltimaDark/issues/94)
- [X] I verified that I am on the latest version
- [X] I verified that ImageEdition, Caching, Service Worker Compatibility and the extension itself are all enabled and that I loaded the site cleanly by closing the tab and opening the URL in a new tab or I flushed it completely with [Tab Suspender](https://www.github.com/Hau-Hau/firefox-tab-suspender)
- [X] I tried disabling caching and refreshing the page several times and it is still broken.
- [X] I confirmed that the target site is not on the excluded sites list or a Mozilla domain on Firefox's protected site listin about:config
- [X] I've searched [known issues](https://www.github.com/ThomazPom/Moz-Ext-UltimaDark/issues) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [README](https://www.github.com/ThomazPom/Moz-Ext-UltimaDark/blob/master/readme.md) and understand how and why to open an issue.

### Site URL

https://quickbooks.intuit.com/

### Provide a description of what about the site is broken and attach screenshots at the bottom

The design is completely broken with all text small and compact.

Before:
![image](https://github.com/user-attachments/assets/e1f0f41c-5aa1-4dae-ac22-0d25202b3299)

After:
![image](https://github.com/user-attachments/assets/db330748-e82e-4408-ae3b-9e87dc21e0f5)

### Provide console logs

- [X] Go to about:debugging#/runtime/this-firefox
- [X] Click "Inspect" on UltimaDark
- [X] Clear the log and refresh the page that is broken
- [X] Copy the WHOLE output and insert it below

### Complete Log

```shell
Ruleset ignored due to bad selector. 3 _generated_background_page.html:1:20
Ruleset ignored due to bad selector. _generated_background_page.html:1:1
Ruleset ignored due to bad selector. 2 _generated_background_page.html:1:25
Ruleset ignored due to bad selector. _generated_background_page.html:1:27
Ruleset ignored due to bad selector. 2 _generated_background_page.html:1:16
Ruleset ignored due to bad selector. _generated_background_page.html:1:41
Ruleset ignored due to bad selector. 2 _generated_background_page.html:1:1
Ruleset ignored due to bad selector. _generated_background_page.html:1:16
Ruleset ignored due to bad selector. _generated_background_page.html:1:1
Ruleset ignored due to bad selector. _generated_background_page.html:1:21
Ruleset ignored due to bad selector. _generated_background_page.html:1:25
Ruleset ignored due to bad selector. 8 _generated_background_page.html:1:13
Ruleset ignored due to bad selector. _generated_background_page.html:1:26
Ruleset ignored due to bad selector. _generated_background_page.html:1:99
Ruleset ignored due to bad selector. _generated_background_page.html:1:27
Ruleset ignored due to bad selector. _generated_background_page.html:1:25
Ruleset ignored due to bad selector. _generated_background_page.html:1:18
Error in parsing value for ‘background-image’.  Declaration dropped. _generated_background_page.html:1:20
Ruleset ignored due to bad selector. 3 _generated_background_page.html:1:16
Ruleset ignored due to bad selector. _generated_background_page.html:1:25
Ruleset ignored due to bad selector. _generated_background_page.html:1:16
Ruleset ignored due to bad selector. 4 _generated_background_page.html:1:59
Ruleset ignored due to bad selector. _generated_background_page.html:1:16
Ruleset ignored due to bad selector. 2 _generated_background_page.html:1:25
Ruleset ignored due to bad selector. _generated_background_page.html:1:34
Ruleset ignored due to bad selector. _generated_background_page.html:1:1
Ruleset ignored due to bad selector. _generated_background_page.html:1:24
Ruleset ignored due to bad selector. _generated_background_page.html:1:124
Error in parsing value for ‘font-family’.  Declaration dropped. _generated_background_page.html:1:126
Ruleset ignored due to bad selector. _generated_background_page.html:1:24
Ruleset ignored due to bad selector. _generated_background_page.html:1:103
```

**Comment by ThomazPom** [comment]
I’m suspectting this issue to be Linked with this https://github.com/ThomazPom/Moz-Ext-UltimaDark/issues/94#issuecomment-2505667736

Could you please confirm this website is not broken in 1.5.77, prior to the temporary drop of these websites?

**Comment by hunkyburrito** [comment]
Just tried v1.5.77 and it is still broken in the same way, but one of the background images does come back unlike the newest version.

v1.5.77:
![image](https://github.com/user-attachments/assets/70dedd04-60c1-45d9-8a1b-4aa4ec5d15f2)

**Comment by ThomazPom** [comment]
This is great news, this means we have a tangible bug to research, i’ll fix soon
