### ISSUE TITLE
[NOT AN ISSUE] Suggested text for AMO' page (Priority Level: Low)

### ISSUE THREAD

**Issue by EstherMoellman** [ThomazPom/Moz-Ext-UltimaDark#16]
UltimaDark uses smart techniques to get a dark mode everywhere on Internet.
Compared to other similar add-ons, UltimaDark has a great output between: "Good Browser Performance" VS "Good Aesthetic Results" (no white-flashing). Loading web-page speed is very good, and RAM/CPU consumption is under control.

Currently UltimaDark is in "experimental stage". That means the add-on still is under development in order to consume less browser resources, while having the best possible aesthetic results. UltimaDark was heavily tested, and it works fine for most of the web-pages. It's worth mentioning that is impossible to build the perfect dark theme add-on (lot of web-pages are badly programmed, and it's not easy to deal with them, every dark-theme add-on has imperfections). In this context, if you find problems, please report here: https://github.com/ThomazPom/Moz-Ext-UltimaDark/issues

Current features:
On/Off switch at icon add-on (pop-up)
White-listing option (*)
Black-listing option (*)

UltimaDark is fully open-source, and doesn't contain any tracking, advertising or privacy infringement.

(*) Match Patterns can be used (https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Match_patterns), and domains with up to 5 elements (x.x.x.com.x) can be white-listed (covering most of the countries and different types of urls)

**Comment by Vintagemotors** [comment]
Can this be closed or is some variation on this still under consideration? Personally, I feel the current description is fine and if someone wants to learn more about the technical details they can read about it in the README for this repository.

**Comment by ThomazPom** [comment]
@Vintagemotors, you're absolutely correct. I've already hit the character limit with the current description.

**Comment by Vintagemotors** [comment]
Closed due to current description being fine and this suggestion exceeding character limit.
