### ISSUE TITLE
Bug with uploaded image (Priority Level: ?)

### ISSUE THREAD

**Issue by EstherMoellman** [ThomazPom/Moz-Ext-UltimaDark#23]
At: https://i.reddit.com/r/FirefoxCSS/comments/hxybh7/can_someone_help_a_noob_i_just_installed_the/.compact

if you click the image link: https://i.redd.it/0efowtlou3d51.png

Then the message appears: **The image "https://i.redd.it/0efowtlou3d51.png" cannot be displayed because it contains errors.**

If you disable UltimaDark... everything works fine.
I also tested same link on www.reddit and old.reddit, and the issue still appears when UltimaDark is enabled.

**Comment by ThomazPom** [comment]
This is the same bug as #7 : Special characters included in image gets  corrupted and so the image itself

**Comment by EstherMoellman** [comment]
Issue closed and moved to #7 in order to keep your GitHub clean and organized.

**Comment by ThomazPom** [comment]
@EstherMoellman  This one was as simple as it was hard, it took me days to figure out how to solve it efficiently  
Next version of UltimaDark will be great

**Comment by EstherMoellman** [comment]
Hi @ThomazPom !
UltimaDark already is great.
And at every update, you're making UltimaDark better and better.
I know, it's a lot of work, and you're breaking your head. But I'm convinced that it's worth it, UltimaDark might be the best darkener add-on ever.
Take all the time you need. You're doing an amazing job. Be proud of yourself.
Kudos for your work!
