### ISSUE TITLE
[NOT AN ISSUE] Suggestion for UltimaDark name (Priority Level: Low)

### ISSUE THREAD

**Issue by EstherMoellman** [ThomazPom/Moz-Ext-UltimaDark#24]
Users looking for darkener add-ons, usually at AMO will use the word "dark" in the search. it is the easiest way to search everything related to dark.

However, if you do a search at AMO using "dark" word, UltimaDark hardly will appear, because "Ultima" and "Dark" are part of the same unified word. Then the search by name will be very difficult. Also the search by relevance will be difficult.

So if you allow me a suggestion, perhaps in the future you can change UltimaDark name for something more simple to be found at AMO' search. For example:
- Smart Dark
- Dark Smart
- Dark Mode Ultima
- Etc

**Comment by ThomazPom** [comment]
Thanks for your name suggestions! I appreciate your effort to make the extension more discoverable.

"Ultima Dark" holds a personal significance for me, representing the " Only one darkening extension i may use" = Ultima. I'm attached to its meaning.

**Comment by Vintagemotors** [comment]
If you did something like "UltimaDark - The Fastest Dark Mode Extension" that would definitely help searchability - I would have been using this when it first came out had I known about it!

**Comment by ThomazPom** [comment]
I like this suffix al lot as it reflects UltimaDark goal, i'll append it to the name in the store , but not yet, i'm just taking time to think about other possible suffix that would help find UltimaDark .

**Comment by ThomazPom** [comment]
![image](https://github.com/ThomazPom/Moz-Ext-UltimaDark/assets/8494601/40079e92-c3d5-4df0-8c73-d0c4c6d4659e)

**Comment by Vintagemotors** [comment]
Closing as it was changed to suggestion on 1/17/2024
