### ISSUE TITLE
Text names of codes (i.e. "white") appears as "rgba(something)" (Priority level: High)

### ISSUE THREAD

**Issue by EstherMoellman** [ThomazPom/Moz-Ext-UltimaDark#25]
Some text word colors such "white", sometimes (not always) appear as "rgba(something)".

Here is an example, look at the title of the posts, with UltimaDark disabled the text word always is "white flash". But with Ultima enabled sometimes it appears as "rgba(30,30,30,1)": https://old.reddit.com/r/FirefoxCSS/search?q=white+flash&restrict_sr=on&sort=relevance&t=all
Curiously, the rgba substitution text word only appears sometimes.

Here is another example, your own post: https://github.com/ThomazPom/Moz-Ext-UltimaDark/issues/6#issuecomment-663240469
With UltimaDark disabled: "I now have very nice colors and white logos".
Ultima enabled: "I now have very nice colors and rgba(30,30,30,1) logos"

EDIT: Even when I write this issue, the bug appears, changing my "whitetext" with "rgba(sometinhg)".

EDIT - UPDATE: Fixed on V1.2.0

**Comment by ThomazPom** [comment]
Yeah, this is the detection expression is too wide, this is probably also why amazon is broken 
https://regex101.com/r/XcItwG/1
