### ISSUE TITLE
Embedded stuff in whitelisted domains are darkened (Priority level: High)

### ISSUE THREAD

**Issue by EstherMoellman** [ThomazPom/Moz-Ext-UltimaDark#26]
For example, at UltimaDark blacklist (exclude) https://miradetodo.co/

Now go to: https://miradetodo.co/archive-2020-720p-hd/
Click "trailers" and watch the youtube trailer (which is embedded), and you'll see UltimaDark darkening the video background (which in this example is bad, because UltimaDark changes youtube dark background to grey).

In same example, but at main movie video player (click "subtitulado"), if you chose "Jawcloud" option, then again black video background is converted to grey.

The fix needed in this case is to whitelist embedded stuff on whitelisted domains.

EDIT: PARTIALLY FIXED V1.2.3... but still has issues.
EDIT2: After V.1.2.4 most of the movie players can't be seen.

**Comment by ThomazPom** [comment]
Hi,
Did you mean _`For example, at UltimaDark blacklist https://miradetodo.co/`_ ?

**Comment by EstherMoellman** [comment]
Hi @ThomazPom ! Yeap you're right, my bad, my apologies. I meant "to exclude https://miradetodo.co" = not darkened.


By the way, you can test this issue also here: https://techxplore.com/news/2019-07-robot-machine-harvest-lettuce.html
This is a very interesting page for UltimaDark, because if the page is darkened (whitelisted), then UltimaDark hides the embedded youtube video. And if the page is blacklisted (excluded), then the embedded youtube video is darkened by UltimaDark.

**Comment by ThomazPom** [comment]
As you said; FIXED V1.2.4
