### ISSUE TITLE
Broken Pages Report (Priority level: High)

### ISSUE THREAD

**Issue by EstherMoellman** [ThomazPom/Moz-Ext-UltimaDark#27]
https://github.com/

FIXED V1.2.3

**Comment by ThomazPom** [comment]
Hi @EstherMoellman 
1.2.2 is online
You may see a lot of regressions, but the code is a lot better, should not break pages anymore and each micro issues like the new york time logo will be easier to fix.
https://edition.cnn.com/2019/07/07/africa/stella-nyanzi-as-equals-intl/index.html
https://www.nytimes.com/
translate.google.com/
https://filmesonline10.net/lancamentos/
See you in the partial darkening issue :)

**Comment by EstherMoellman** [comment]
@ThomazPom mon ami, thank you and kudos for the latest V1.2.2

Yeah, I posted a lot of new issues. But it doesn't mean that V1.2.2 worsen. This just means I did a major test... so naturally, more issues appeared. Totally normal! And considering I tested hundred of webpages, you can see that the total of reported issues is minimum when compared to the amount of tested webpages. I still believe UltimaDark is working well for at least 85% of the webpages... and IMO this is excellent, not perfect, but excellent. Congratulations for your great work!

**Comment by EstherMoellman** [comment]
https://translate.google.com/
Top header is white. FIXED V1.2.3
REGRESSION V.1.2.5

**Comment by ThomazPom** [comment]
https://translate.google.com/ was a conflict between Ultimadark and their code using the same variable name (window.ud) i just fixed it by renaming my window.ud into window.uDark, avoiding the collision

**Comment by EstherMoellman** [comment]
https://www.theguardian.com/international
REGRESSION V1.2.5
FIXED V1.2.6
REGRESSION V.1.3.3 (broken page)

**Comment by ThomazPom** [comment]
Not broken anymore !
