### ISSUE TITLE
Domains with TLDs with multiple "parts" break when adding exception

### ISSUE THREAD

**Issue by Tanza3D** [ThomazPom/Moz-Ext-UltimaDark#33]
For example: adding an exception for "amazon.co.uk` adds an exception for "co.uk" and "*.co.uk". This is an issue for any site with domains with two or more parts, like gov.uk and other sites like such.

**Comment by ThomazPom** [comment]
Hi. I'm sorry if the "**precision**" selector below the exclude button is unclear, however i just tested it , it works as intended.
