### ISSUE TITLE
Broken Webpages Report (Priority level: High)

### ISSUE THREAD

**Issue by EstherMoellman** [ThomazPom/Moz-Ext-UltimaDark#4]
https://edition.cnn.com/2019/07/07/africa/stella-nyanzi-as-equals-intl/index.html

**Comment by ThomazPom** [comment]
I just published a minute ago the 1.1.4 version, could you take a look ?

**Comment by EstherMoellman** [comment]
Totally solved in V1.1.4 (beautiful).
Congrats and thank you!
