### ISSUE TITLE
Edit for clarity: dark blue is being changed to a medium purple in some cases ____________________ Formerly: Some websites exhibit purple section headers instead of white. 

### ISSUE THREAD

**Issue by Vintagemotors** [ThomazPom/Moz-Ext-UltimaDark#40]
Edit: studyabacus.com is behaving as intended - I just couldn't see that the source color was a very dark purple. ~~Example of issue: https://studyabacus.com/classes/abacus-basic~~
Example of expected behavior: https://www.w3schools.com/w3css/w3css_templates.asp
Craigslist homepage also exhibits this: https://losangeles.craigslist.org/ 
FTP sites appear to also exhibit this with their links being purple implying they have already been clicked instead of blue: https://archive.xfce.org/

Let me know if I should close this and add a comment [here](https://github.com/ThomazPom/Moz-Ext-UltimaDark/issues/6)

**Comment by ThomazPom** [comment]
Thank you for pointing out this .

Texts on  https://studyabacus.com/classes/abacus-basic are in fact purple and one of UtilmaDark main goals is to respect the original theme of websites, i'ts why the equivalent color for studyabacus menu items is this light purple.

I will need to make a decision regarding such dark but colorized items, as generating pastel colors on dark backgrounds may not result in an aesthetically pleasing appearance.

![image](https://github.com/ThomazPom/Moz-Ext-UltimaDark/assets/8494601/8981ccb8-2c28-48fd-ab30-d5efbad3eef6)

Same behavoiur on craiglist
![image](https://github.com/ThomazPom/Moz-Ext-UltimaDark/assets/8494601/198ddc8c-4178-4f0d-add9-20cd1f732013)

**Comment by Vintagemotors** [comment]
![image](https://github.com/ThomazPom/Moz-Ext-UltimaDark/assets/103160565/093b2d44-f5f1-4218-9df6-b27a2df04d1d)
![image](https://github.com/ThomazPom/Moz-Ext-UltimaDark/assets/103160565/e1b0fcea-e48c-4b41-8498-46df3bc5d0a8)
Sorry, I should have been clearer when explaining the issue. Color target is the "S" in Los Angeles

**Comment by Vintagemotors** [comment]
I can see now for studyabacus.com that their source color is a very dark purple, it just looked black on the monitor I was testing with. 
![image](https://github.com/ThomazPom/Moz-Ext-UltimaDark/assets/103160565/3308ab42-7f3f-4df4-ab1f-2ade50c1eb5b)
![image](https://github.com/ThomazPom/Moz-Ext-UltimaDark/assets/103160565/ceeca612-b131-4e30-b986-5124ec3727dc)

**Comment by ThomazPom** [comment]
As you know, each color is adjusted for better visibility. ( Often brighter for texts colors )
No brightening for this color may result in poor visibility, as illustrated below:
![image](https://github.com/ThomazPom/Moz-Ext-UltimaDark/assets/8494601/26a98fa1-254c-4756-9636-81d093ae79a7)

Adding brightness to a pure blue ends feeling of purple if displayed on dark background, but in fact I't still a pure blue ( as red and green RGB value are equals)


Craigslist's blue : https://hslpicker.com/#00E
![image](https://github.com/ThomazPom/Moz-Ext-UltimaDark/assets/8494601/c689c653-0b40-472a-a3a9-3c9f42afccad)

Craigslist's blue + 20 of lightness https://hslpicker.com/#5757ff ( see the 87, 87 values for red and green )
![image](https://github.com/ThomazPom/Moz-Ext-UltimaDark/assets/8494601/34b179e5-b794-44dc-8e29-1a2e2425c425)

Adding a bit of negative shift may help prevent the illusion, this may be a setting of UltimaDark ( see the 87, 171 values for red and green: It's not anymore a pure blue ) . This could be a very cool setting of UltimaDark
![image](https://github.com/ThomazPom/Moz-Ext-UltimaDark/assets/8494601/b9df6d65-0e62-4cd8-bc44-92279cd2fce3)


About FTP links, as the [text color transformation function shows](https://www.desmos.com/calculator/pnfko9zcei). The more a text has a brightness far from 50% the more it gets brightened, from a minimum of 65%(A) of brightness up to 85%(B) of brightness( 100% of brightness on a black background is not very pleasant, but all of these values will be adjustable in uDark's panel).
This is why originally darkened links ( like clicked ones, ends brightened like for FTP )
![image](https://github.com/ThomazPom/Moz-Ext-UltimaDark/assets/8494601/45d504c0-acea-4e8c-9ea1-93b327c0a984)

**Comment by ThomazPom** [comment]
I did very little experiment in the  1.5.21 about this
> Adding brightness to a pure blue ends feeling of purple if displayed on dark background, but in fact I't still a pure blue ( as red and green RGB value are equals)

As far as i experienced, this annoying illusion happens only with blue text with increased luminance : 

Green feels nice :
![image](https://github.com/ThomazPom/Moz-Ext-UltimaDark/assets/8494601/905fb83f-72cb-4e62-92fb-1abf7f0c39f4)
Red feels nice 
![image](https://github.com/ThomazPom/Moz-Ext-UltimaDark/assets/8494601/38452838-004b-4d13-a848-4f0445943629)
Blue is still blue, but annoying to read as text on pure blue hue ( 240/360 = 0.666% ) 
![image](https://github.com/ThomazPom/Moz-Ext-UltimaDark/assets/8494601/79de0ba4-ccdb-45da-a6a7-5ff6517f823b)

In this experiment a blue-ish color (237.6 up to 259.2) gets lighten over 0.6, bellow illustrated experimental code will shift its hue by -0.06% = -21.6 of 360

![image](https://github.com/ThomazPom/Moz-Ext-UltimaDark/assets/8494601/41d8a0e7-4ae2-4331-a40b-6844d7cb7c01)

Obtaining the following result :
![image](https://github.com/ThomazPom/Moz-Ext-UltimaDark/assets/8494601/46da64c6-5101-416d-9cb8-7ed85c3c63dd)

Thell me your toughs about this.

**Comment by Vintagemotors** [comment]
I have no idea what is going on with Github right now but I can't see any of the images you attached here or my own, tested on 2 different devices and different Firefox and Chromium builds.

**Comment by Vintagemotors** [comment]
> I did very little experiment in the 1.5.21 about this

It looks much better with the blue links! This is great for now but as you have mentioned and as was mentioned by another issue in the past, being able to define link replacement colors per page and globally would be a great feature for the future. 

Embedding screenshot via Discord since it is still visible:

![](https://cdn.discordapp.com/attachments/624403666425872405/1190071765263712318/image.png)

**Comment by Vintagemotors** [comment]
Closed because it has been aggregated here: https://github.com/ThomazPom/Moz-Ext-UltimaDark/issues/53
