### ISSUE TITLE
On some websites scroll bar is not recolored 

### ISSUE THREAD

**Issue by Vintagemotors** [ThomazPom/Moz-Ext-UltimaDark#42]
Example site where it doesn't work: https://www.muskokaseaflea.ca/homesplash/
Example site where it works as expected: https://store.muskokaseaflea.ca/index.php?route=product/category&path=33#new_tab

**Comment by ThomazPom** [comment]
Thank you for highlighting these instances 👍. I had considered scrollbars once but then forgot about them. This issue will serve as a great reminder.

**Comment by atomGit** [comment]
hey @Vintagemotors - you might want to add these test cases to #36 to keep things neat (and Thomaz might appreciate sticky-ing it) - if you, as a contributor, have sufficient permission to edit my posts you can just edit the 1st post, else add them in the chain and i'll handle it

**Comment by Vintagemotors** [comment]
It is a separate and ongoing issue. I can add it to test sites but this should remain open for tracking.

**Comment by ThomazPom** [comment]
Scrollbar colors can either be white or dependent on the website's background color.

Modifying it with UltimaDark is straightforward, but I'm wondering of the optimal color logic for it.

The simplest approach might involve two fixed colors: a dark grey for the scrollbar thumb and nearly black for the scrollbar track. However, incorporating an alpha value could reproduce in some sort the original relation between scrollbar color and.

https://codepen.io/Thomaz-Pom/pen/qBvRWvB

Scrollbars from left to right in above snippet:
-   Native to Firefox
-   Dark grey for the scrollbar thumb and nearly black for the scrollbar track
-   Emulation of the native appearance without switching to white on the brightest backgrounds (which doesn't occur with UltimaDark anyway)
-   Similar to 3, but with a dark thumb.
-   Swapped colors from 2.

**Comment by Vintagemotors** [comment]
3 is mostly there but allows it to get a bit too bright 
![image](https://github.com/ThomazPom/Moz-Ext-UltimaDark/assets/103160565/8176f369-d601-4e7c-be1f-b60eb076eeca)
![image](https://github.com/ThomazPom/Moz-Ext-UltimaDark/assets/103160565/1d62ae4b-367b-4e85-897c-3c9fffe7d7ef)

**Comment by ThomazPom** [comment]
I've put them side to side, to be sure, on your brightest example and the colour of the scrollbar thumb is the exact same
![image](https://github.com/ThomazPom/Moz-Ext-UltimaDark/assets/8494601/3c219f72-5dee-4edc-86ff-ca83bef16824)
There is a small difference with the track. I'll adapt the snippet

**Comment by ThomazPom** [comment]
![image](https://github.com/ThomazPom/Moz-Ext-UltimaDark/assets/8494601/44d73db0-d7aa-412b-afad-21f495cc30ab)
#col3{
	scrollbar-color:rgba(255,255,255,0.40) rgba(0,0,0,0.26)
}

**Comment by ThomazPom** [comment]
I would consider it satisfactory. The presence of an alpha channel in the scrollbar thumb means that altering the track with rgba(0,0,0,0.26) has an impact on the color rgba(255,255,255,0.40) of the scrollbar thumb. Investigating the precise match would require adjusting the 0.0.0.0.26 values within the range of 0 to 30 and the 0.15 to 0.40 values approximately, as well as the 255.255.255.40 values from 235 to 255 and the 0.25 to 0.65 values approximately. However, delving into such time consuming fine-tuned adjustments may not be justified.

**Comment by ThomazPom** [comment]
I like all four options, but with an infinite number of color combinations, how do we choose the best one?

**Comment by Vintagemotors** [comment]
![image](https://github.com/ThomazPom/Moz-Ext-UltimaDark/assets/103160565/fa2c9521-7e29-4922-9570-2b3e24fdcc32)
Reducing the opacity for the background after it reaches a certain brightness threshold seems like a reasonable compromise though I don't know whether it really matters assuming UltimaDark would be preventing colors this light anyways.

**Comment by ThomazPom** [comment]
I won't tweak scrollbar opacity based on brightness because it processing for such a simple thing as scrollbars. Doing this would mean figuring out each scrollable part, adjusting opacity during load, and updating it whenever the background or its background-color changes. It's just not practical for managing scrollbars, especially if the background comes from images. Let's stick to the basics and use two fixed colors, whether with or without transparency.

**Comment by Vintagemotors** [comment]
3rd option with user defined global colors and no transparency or fixed opacity?

**Comment by ThomazPom** [comment]
The default setting will be the third option, but users will be able to customize their preferred colors, including opacity. We'll also provide one-click options for suggested styles 1 to 4.

**Comment by Vintagemotors** [comment]
Resolved in 1.5.34
