### ISSUE TITLE
UltimaDark turns the speedtest.net tab favicon white 

### ISSUE THREAD

**Issue by Vintagemotors** [ThomazPom/Moz-Ext-UltimaDark#45]
https://www.speedtest.net/

normal 
![image](https://github.com/ThomazPom/Moz-Ext-UltimaDark/assets/103160565/40887e14-f51c-45bc-ae31-81bc8559700f)

enabled 
![image](https://github.com/ThomazPom/Moz-Ext-UltimaDark/assets/103160565/78ce3213-8225-40ff-bebc-da76600a3679)

**Comment by ThomazPom** [comment]
Thanks for your feedback.
The image editing feature in UltimaDark is currently experimental and broken.
I'll be working on fixing it over the next few weeks. Meanwhile, you can disable image editing in the UltimaDark panel if it bother you.

**Comment by ThomazPom** [comment]
I'm unable to replicate this issue. Could you share a screenshot for clarification?

By the way, thank you for submitting your issues along with helpful examples. I greatly appreciate it.

**Comment by Vintagemotors** [comment]
Fixed in the rewrite.
