### ISSUE TITLE
Icons fail to load while UltimaDark is enabled and Image Edition is disabled 

### ISSUE THREAD

**Issue by Vintagemotors** [ThomazPom/Moz-Ext-UltimaDark#47]
Incorrect behavior
![image](https://github.com/ThomazPom/Moz-Ext-UltimaDark/assets/103160565/fb54e121-216f-4057-a26a-9e026e3e3460)

Expected behavior 
![image](https://github.com/ThomazPom/Moz-Ext-UltimaDark/assets/103160565/d2a63e4b-1231-4b4a-ac30-778300fbc3aa)

Page link: https://addons.palemoon.org/themes/

**Comment by ThomazPom** [comment]
Fixed in version 1.5.20 along with a few rare text coloring issues !
Thanks for catching that, Your feedback is always appreciated.

**Comment by Vintagemotors** [comment]
Can confirm it is now fixed, well done!

**Comment by Vintagemotors** [comment]
If persisting, manually check for updates then install 1.5.20 or higher and refresh the page.
