### ISSUE TITLE
Darkening Not Working Report (Priority level: High)

### ISSUE THREAD

**Issue by EstherMoellman** [ThomazPom/Moz-Ext-UltimaDark#5]

**Comment by ThomazPom** [comment]
Note;
Do not forget var( edits for text colors with a -fg prefix

**Comment by EstherMoellman** [comment]
V.1.1.5:

www.facebook.com

https://filmesonline10.net/lancamentos/

**Comment by ThomazPom** [comment]
1.2.0 is online
I mostly fixed bugs, this helped websites to be  ok including facebook

**Comment by EstherMoellman** [comment]
https://edition.cnn.com/travel/article/first-flight-largest-electric-aircraft-scli-intl/index.html
https://edition.cnn.com/style/article/yulia-tsvetkova-pornography-gay-propaganda-law-lgbtq-activism-russia/index.html

https://userstyles.org

https://extra.globo.com/noticias/celular-e-tecnologia/robo-da-mortal-para-tras-impressiona-por-movimentos-quase-humanos-video-22084728.html

**Comment by EstherMoellman** [comment]
https://www.youtube.com

**Comment by EstherMoellman** [comment]
https://www.instagram.com/

**Comment by EstherMoellman** [comment]
walmart.com

**Comment by EstherMoellman** [comment]
linkedin.com

**Comment by EstherMoellman** [comment]
play.google.com

**Comment by EstherMoellman** [comment]
healthline.com

**Comment by EstherMoellman** [comment]
target.com

**Comment by EstherMoellman** [comment]
weather.com

**Comment by EstherMoellman** [comment]
dictionary.com

**Comment by EstherMoellman** [comment]
zillow.com

**Comment by EstherMoellman** [comment]
theguardian.com

**Comment by EstherMoellman** [comment]
usatoday.com

**Comment by EstherMoellman** [comment]
medicalnewstoday.com

**Comment by EstherMoellman** [comment]
https://www.institutomillenium.org.br/correios-discutindo-o-fracasso

**Comment by EstherMoellman** [comment]
https://www.ghacks.net/2020/07/31/windows-10-apps-killer-app-bloatbox-introduces-handy-scripts-support/

**Comment by EstherMoellman** [comment]
https://edition.cnn.com/travel/article/first-flight-largest-electric-aircraft-scli-intl/index.html
https://edition.cnn.com/style/article/yulia-tsvetkova-pornography-gay-propaganda-law-lgbtq-activism-russia/index.html

https://userstyles.org

https://extra.globo.com/noticias/celular-e-tecnologia/robo-da-mortal-para-tras-impressiona-por-movimentos-quase-humanos-video-22084728.html

https://filmesonline10.net/lancamentos/

https://www.youtube.com

https://www.instagram.com/

microsoft.com

target.com

https://weather.com/

**Comment by ThomazPom** [comment]
1.2.4 is online.

The main thing i did was to start to re enabling and get working the part of the code i mentioned precedently disabled on purpose. (lot of work there)

I did not fully enabled this special part of the code designed to live edit the style of new created elements after the first load (like banner cookies), but that was enough for getting YouTube in dark mode and probably many websites with this kind of after loading technology.

I also improved speed, performance and stability

**Comment by EstherMoellman** [comment]
https://edition.cnn.com/travel/article/first-flight-largest-electric-aircraft-scli-intl/index.html
https://edition.cnn.com/style/article/yulia-tsvetkova-pornography-gay-propaganda-law-lgbtq-activism-russia/index.html

https://userstyles.org

https://extra.globo.com/noticias/celular-e-tecnologia/robo-da-mortal-para-tras-impressiona-por-movimentos-quase-humanos-video-22084728.html

https://filmesonline10.net/lancamentos/

https://www.instagram.com/

http://microsoft.com/

https://www.target.com/

https://weather.com/

**Comment by EstherMoellman** [comment]
https://www.google.com/
FIXED V1.2.3

https://www.walmart.com/
FIXED V1.2.3

https://www.linkedin.com/
FIXED V1.2.3

https://play.google.com/store
FIXED V1.2.3

https://www.healthline.com/
FIXED V1.2.3

https://www.dictionary.com/
FIXED V1.2.3

https://www.usatoday.com/
FIXED V1.2.3

https://www.medicalnewstoday.com/
FIXED V1.2.3

https://www.institutomillenium.org.br/correios-discutindo-o-fracasso/
FIXED V1.2.3

https://www.ghacks.net/2020/07/31/windows-10-apps-killer-app-bloatbox-introduces-handy-scripts-support/
FIXED V1.2.3

https://www.youtube.com
FIXED V1.2.4

**Comment by EstherMoellman** [comment]
https://edition.cnn.com/travel/article/first-flight-largest-electric-aircraft-scli-intl/index.html
https://edition.cnn.com/style/article/yulia-tsvetkova-pornography-gay-propaganda-law-lgbtq-activism-russia/index.html

https://userstyles.org

https://extra.globo.com/noticias/celular-e-tecnologia/robo-da-mortal-para-tras-impressiona-por-movimentos-quase-humanos-video-22084728.html

https://filmesonline10.net/lancamentos/

https://www.instagram.com/

http://microsoft.com/

https://www.target.com/

https://weather.com/

**Comment by ThomazPom** [comment]
1.2.6 is online,
As this version is now now "forced" to use browser own cache (i could bypass it but this would not be great) you may have to clear your cache and your localstorage, or try UltimaDark in private mode,  or refresh white page ( if you get one ) by mainaining CTRL then SHIFT then R at the same time

This version introduces more darkening on elements that are side loaded/lazy loaded after the first load.
This version now differenciate web pages and stylesheets over the rest of ressources, solving pdf's and images and whatever broken when loaded ina  separate tab

**Comment by ThomazPom** [comment]
1.2.7 is online : 
1. More darkening on elements that are side loaded/lazy loaded after the first load. (CNN is now covered, i'm glad of this one)
2. Better management of browser own cache
3.  Better performance

**Comment by ThomazPom** [comment]
1.2.8 is online and fixes background contrast issues i had since 1.2.6

**Comment by EstherMoellman** [comment]
https://userstyles.org

https://extra.globo.com/noticias/celular-e-tecnologia/robo-da-mortal-para-tras-impressiona-por-movimentos-quase-humanos-video-22084728.html

https://filmesonline10.net/lancamentos/

https://www.instagram.com/

http://microsoft.com/

https://weather.com/

https://www.google.com/
FIXED V1.2.3
REGRESSION V1.2.8 (see image: https://imgur.com/a/0Uy8FI9)

**Comment by EstherMoellman** [comment]
https://www.walmart.com/
FIXED V1.2.3

https://www.linkedin.com/
FIXED V1.2.3

https://play.google.com/store
FIXED V1.2.3

https://www.healthline.com/
FIXED V1.2.3

https://www.dictionary.com/
FIXED V1.2.3

https://www.usatoday.com/
FIXED V1.2.3

https://www.medicalnewstoday.com/
FIXED V1.2.3

https://www.institutomillenium.org.br/correios-discutindo-o-fracasso/
FIXED V1.2.3

https://www.ghacks.net/2020/07/31/windows-10-apps-killer-app-bloatbox-introduces-handy-scripts-support/
FIXED V1.2.3

https://www.youtube.com
FIXED V1.2.4

https://www.target.com/
FIXED V1.2.6

https://edition.cnn.com/travel/article/first-flight-largest-electric-aircraft-scli-intl/index.html
https://edition.cnn.com/style/article/yulia-tsvetkova-pornography-gay-propaganda-law-lgbtq-activism-russia/index.html
FIXED V1.2.8

https://weather.com/
FIXED V1.2.8

**Comment by EstherMoellman** [comment]
https://userstyles.org

https://extra.globo.com/noticias/celular-e-tecnologia/robo-da-mortal-para-tras-impressiona-por-movimentos-quase-humanos-video-22084728.html

https://filmesonline10.net/lancamentos/

https://www.instagram.com/

http://microsoft.com/

https://www.google.com/
FIXED V1.2.3
REGRESSION V1.2.8 (see image: https://imgur.com/a/0Uy8FI9)

**Comment by ThomazPom** [comment]
1.2.9 fixes litle logos bugs and other technical things. 
On your example, google is not a regression, you just did too much calls to google servers, and its asking you if you are not some sort of malicious bot

**Comment by EstherMoellman** [comment]
> google is not a regression, you just did too much calls to google servers

... hummmm, I don't think so : )
If I disable UltimaDark, google works perfect.

**Comment by ThomazPom** [comment]
1.3.2 is online.
This was not easy.

**Comment by ThomazPom** [comment]
https://extra.globo.com/ is in fact a partial darkening issue asn only the background stays white, i have to catch this :)

**Comment by EstherMoellman** [comment]
https://www.walmart.com/
FIXED V1.2.3

https://www.linkedin.com/
FIXED V1.2.3

https://play.google.com/store
FIXED V1.2.3

https://www.healthline.com/
FIXED V1.2.3

https://www.dictionary.com/
FIXED V1.2.3

https://www.usatoday.com/
FIXED V1.2.3

https://www.medicalnewstoday.com/
FIXED V1.2.3

https://www.institutomillenium.org.br/correios-discutindo-o-fracasso/
FIXED V1.2.3

https://www.ghacks.net/2020/07/31/windows-10-apps-killer-app-bloatbox-introduces-handy-scripts-support/
FIXED V1.2.3

https://www.youtube.com
FIXED V1.2.4

https://www.target.com/
FIXED V1.2.6

https://edition.cnn.com/travel/article/first-flight-largest-electric-aircraft-scli-intl/index.html
https://edition.cnn.com/style/article/yulia-tsvetkova-pornography-gay-propaganda-law-lgbtq-activism-russia/index.html
FIXED V1.2.8

https://weather.com/
FIXED V1.2.8

https://www.google.com/
FIXED V1.2.3
REGRESSION V1.2.8 (see image: https://imgur.com/a/0Uy8FI9)
FIXED V1.2.9

https://userstyles.org
FIXED V1.3.2

https://filmesonline10.net/lancamentos/
FIXED V1.3.2

http://microsoft.com/
FIXED V1.3.2

**Comment by EstherMoellman** [comment]
https://extra.globo.com/noticias/celular-e-tecnologia/robo-da-mortal-para-tras-impressiona-por-movimentos-quase-humanos-video-22084728.html

https://www.instagram.com/

**Comment by ThomazPom** [comment]
Some mozilla websites such as accounts.firefox.com & addons.mozilla.com can't be reached by addons for security reasons :
As i'm able to edit the page  i then could force you to set a ★★★★★ on https://addons.mozilla.org/fr/firefox/addon/ultimadark/reviews/

**Comment by EstherMoellman** [comment]
https://www.linkedin.com/
FIXED V1.2.3

https://play.google.com/store
FIXED V1.2.3

https://www.healthline.com/
FIXED V1.2.3

https://www.dictionary.com/
FIXED V1.2.3

https://www.usatoday.com/
FIXED V1.2.3

https://www.medicalnewstoday.com/
FIXED V1.2.3

https://www.institutomillenium.org.br/correios-discutindo-o-fracasso/
FIXED V1.2.3

https://www.ghacks.net/2020/07/31/windows-10-apps-killer-app-bloatbox-introduces-handy-scripts-support/
FIXED V1.2.3

https://www.youtube.com
FIXED V1.2.4

https://www.target.com/
FIXED V1.2.6

https://edition.cnn.com/travel/article/first-flight-largest-electric-aircraft-scli-intl/index.html
https://edition.cnn.com/style/article/yulia-tsvetkova-pornography-gay-propaganda-law-lgbtq-activism-russia/index.html
FIXED V1.2.8

https://weather.com/
FIXED V1.2.8

https://www.google.com/
FIXED V1.2.3
REGRESSION V1.2.8 (see image: https://imgur.com/a/0Uy8FI9)
FIXED V1.2.9

https://userstyles.org
FIXED V1.3.2

https://filmesonline10.net/lancamentos/
FIXED V1.3.2

http://microsoft.com/
FIXED V1.3.2

**Comment by EstherMoellman** [comment]
https://www.instagram.com/

**Comment by ThomazPom** [comment]
Instagram & Site usig the same strategy as instagram are covered in 1.3.5

**Comment by ThomazPom** [comment]
1.4.5 REGRESSION ON TITLE AND TOP BAR
https://edition.cnn.com/travel/article/first-flight-largest-electric-aircraft-scli-intl/index.html
https://edition.cnn.com/style/article/yulia-tsvetkova-pornography-gay-propaganda-law-lgbtq-activism-russia/index.html

**Comment by ThomazPom** [comment]
Checked all websites, all good
