### ISSUE TITLE
Unusable on MyPal68

### ISSUE THREAD

**Issue by Vintagemotors** [ThomazPom/Moz-Ext-UltimaDark#51]
Browser version: latest 32 bit https://github.com/Feodor2/Mypal68/releases/tag/68.13.7b
OS: Windows Vista 32 bit with all ESR patches 
Extension version: 1.5.22 

## What Isn't working? 
Basically every page is either completely blank or loads as base html when the extension is enabled at all. 

## Logs 

[Exception... "File error: Not found"  nsresult: "0x80520012 (NS_ERROR_FILE_NOT_FOUND)"  location: "JS frame :: jar:file:///C:/Program%20Files/mypal-68.13.7.en-US.win32/mypal/browser/features/webcompat@mozilla.org.xpi!/experiment-apis/pictureInPicture.js :: getPolicies :: line 70"  data: no] pictureInPicture.js:70:11
Error: An unexpected error occurred undefined:14:57
Error: Incorrect argument types for pictureInPictureParent.setOverrides. picture_in_picture_overrides.js:15:36
Error processing colors.toolbar_text: Please use <em>theme.colors.bookmark_text</em>, this alias will be removed in Firefox 69. background.js:2620
TypeError: Illegal constructor. background.js:457:25
TypeError: Argument 1 of PrecompiledScript.executeInGlobal is not an object. 4 ExtensionContent.jsm:552:25
Type error for parameter contentScriptOptions (Error processing css.0: Value must either: contain the required "file" property, or .code must be a string value) for contentScripts.register. background.js:395
TypeError: Illegal constructor. 6 background.js:1769:29
TypeError: details.frameAncestors is undefined
7 background.js:1838:29
TypeError: Illegal constructor. 6 background.js:1769:29
TypeError: Illegal constructor. 19 background.js:1769:29
Type error for parameter contentScriptOptions (Error processing css.0: Value must either: contain the required "file" property, or .code must be a string value) for contentScripts.register. background.js:395
Type error for parameter contentScriptOptions (Error processing css.0: Value must either: contain the required "file" property, or .code must be a string value) for contentScripts.register. background.js:395
Type error for parameter contentScriptOptions (Error processing css.0: Value must either: contain the required "file" property, or .code must be a string value) for contentScripts.register. 2 background.js:395
Type error for parameter contentScriptOptions (Error processing css.0: Value must either: contain the required "file" property, or .code must be a string value) for contentScripts.register. background.js:395
Type error for parameter contentScriptOptions (Error processing css.0: Value must either: contain the required "file" property, or .code must be a string value) for contentScripts.register. background.js:395
TypeError: details.frameAncestors is undefined
2 background.js:1838:29
Type error for parameter contentScriptOptions (Error processing css.0: Value must either: contain the required "file" property, or .code must be a string value) for contentScripts.register. 2 background.js:395
Type error for parameter contentScriptOptions (Error processing css.0: Value must either: contain the required "file" property, or .code must be a string value) for contentScripts.register. background.js:395
Type error for parameter contentScriptOptions (Error processing css.0: Value must either: contain the required "file" property, or .code must be a string value) for contentScripts.register. background.js:395
Type error for parameter contentScriptOptions (Error processing css.0: Value must either: contain the required "file" property, or .code must be a string value) for contentScripts.register. background.js:395
Type error for parameter contentScriptOptions (Error processing css.0: Value must either: contain the required "file" property, or .code must be a string value) for contentScripts.register. background.js:395
Type error for parameter contentScriptOptions (Error processing css.0: Value must either: contain the required "file" property, or .code must be a string value) for contentScripts.register. background.js:395
Type error for parameter contentScriptOptions (Error processing css.0: Value must either: contain the required "file" property, or .code must be a string value) for contentScripts.register. background.js:395
TypeError: details.frameAncestors is undefined
background.js:1838:29
Type error for parameter contentScriptOptions (Error processing css.0: Value must either: contain the required "file" property, or .code must be a string value) for contentScripts.register. background.js:395
TypeError: details.frameAncestors is undefined
background.js:1838:29
Type error for parameter contentScriptOptions (Error processing css.0: Value must either: contain the required "file" property, or .code must be a string value) for contentScripts.register. background.js:395
Type error for parameter contentScriptOptions (Error processing css.0: Value must either: contain the required "file" property, or .code must be a string value) for contentScripts.register. background.js:395
Type error for parameter contentScriptOptions (Error processing css.0: Value must either: contain the required "file" property, or .code must be a string value) for contentScripts.register. 2 background.js:395
Type error for parameter contentScriptOptions (Error processing css.0: Value must either: contain the required "file" property, or .code must be a string value) for contentScripts.register. background.js:395
Type error for parameter contentScriptOptions (Error processing css.0: Value must either: contain the required "file" property, or .code must be a string value) for contentScripts.register. background.js:395
Type error for parameter contentScriptOptions (Error processing css.0: Value must either: contain the required "file" property, or .code must be a string value) for contentScripts.register. background.js:395
Type error for parameter contentScriptOptions (Error processing css.0: Value must either: contain the required "file" property, or .code must be a string value) for contentScripts.register. background.js:395
Type error for parameter contentScriptOptions (Error processing css.0: Value must either: contain the required "file" property, or .code must be a string value) for contentScripts.register. background.js:395
Type error for parameter contentScriptOptions (Error processing css.0: Value must either: contain the required "file" property, or .code must be a string value) for contentScripts.register. background.js:395
Type error for parameter contentScriptOptions (Error processing css.0: Value must either: contain the required "file" property, or .code must be a string value) for contentScripts.register. background.js:395
Type error for parameter contentScriptOptions (Error processing css.0: Value must either: contain the required "file" property, or .code must be a string value) for contentScripts.register. background.js:395
Security Error: Content at moz-extension://0509c4ae-d72e-4bf3-8039-31da0f19db40/ may not load data from blob:null/9dec1056-c568-4b4b-83f6-d29a9af18472.
[Exception... "Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIDOMWindowUtils.removeSheetUsingURIString]"  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: resource://gre/modules/ExtensionCommon.jsm :: runSafeSyncWithoutClone :: line 73"  data: no] ExtensionCommon.jsm:73:12
TypeError: Argument 1 of PrecompiledScript.executeInGlobal is not an object. ExtensionContent.jsm:552:25
Type error for parameter contentScriptOptions (Error processing css.0: Value must either: contain the required "file" property, or .code must be a string value) for contentScripts.register. background.js:395
Type error for parameter contentScriptOptions (Error processing css.0: Value must either: contain the required "file" property, or .code must be a string value) for contentScripts.register. background.js:395
Type error for parameter contentScriptOptions (Error processing css.0: Value must either: contain the required "file" property, or .code must be a string value) for contentScripts.register. 2 background.js:395
Type error for parameter contentScriptOptions (Error processing css.0: Value must either: contain the required "file" property, or .code must be a string value) for contentScripts.register. background.js:395
Type error for parameter contentScriptOptions (Error processing css.0: Value must either: contain the required "file" property, or .code must be a string value) for contentScripts.register. 2 background.js:395
TypeError: can't access dead object
TooltipTextProvider.jsm:15:7
TypeError: details.frameAncestors is undefined
background.js:1838:29
TypeError: Illegal constructor. background.js:1769:29
Security Error: Content at moz-extension://0509c4ae-d72e-4bf3-8039-31da0f19db40/ may not load data from blob:null/4b44dc83-c55a-4924-83b0-3323a3a028d2.
TypeError: Argument 1 of PrecompiledScript.executeInGlobal is not an object. ExtensionContent.jsm:552:25
Type error for parameter contentScriptOptions (Error processing css.0: Value must either: contain the required "file" property, or .code must be a string value) for contentScripts.register. background.js:395
Type error for parameter contentScriptOptions (Error processing css.0: Value must either: contain the required "file" property, or .code must be a string value) for contentScripts.register. background.js:395
Type error for parameter contentScriptOptions (Error processing css.0: Value must either: contain the required "file" property, or .code must be a string value) for contentScripts.register. background.js:395
Type error for parameter contentScriptOptions (Error processing css.0: Value must either: contain the required "file" property, or .code must be a string value) for contentScripts.register. background.js:395
Type error for parameter contentScriptOptions (Error processing css.0: Value must either: contain the required "file" property, or .code must be a string value) for contentScripts.register. background.js:395
Type error for parameter contentScriptOptions (Error processing css.0: Value must either: contain the required "file" property, or .code must be a string value) for contentScripts.register. background.js:395
Type error for parameter contentScriptOptions (Error processing css.0: Value must either: contain the required "file" property, or .code must be a string value) for contentScripts.register. background.js:395
Type error for parameter contentScriptOptions (Error processing css.0: Value must either: contain the required "file" property, or .code must be a string value) for contentScripts.register. background.js:395
Type error for parameter contentScriptOptions (Error processing css.0: Value must either: contain the required "file" property, or .code must be a string value) for contentScripts.register. background.js:395
Type error for parameter contentScriptOptions (Error processing css.0: Value must either: contain the required "file" property, or .code must be a string value) for contentScripts.register. background.js:395
Type error for parameter contentScriptOptions (Error processing css.0: Value must either: contain the required "file" property, or .code must be a string value) for contentScripts.register. background.js:395
Type error for parameter contentScriptOptions (Error processing css.0: Value must either: contain the required "file" property, or .code must be a string value) for contentScripts.register. background.js:395
Type error for parameter contentScriptOptions (Error processing css.0: Value must either: contain the required "file" property, or .code must be a string value) for contentScripts.register. background.js:395
Type error for parameter contentScriptOptions (Error processing css.0: Value must either: contain the required "file" property, or .code must be a string value) for contentScripts.register. background.js:395
Type error for parameter contentScriptOptions (Error processing css.0: Value must either: contain the required "file" property, or .code must be a string value) for contentScripts.register. background.js:395
Type error for parameter contentScriptOptions (Error processing css.0: Value must either: contain the required "file" property, or .code must be a string value) for contentScripts.register. background.js:395
Type error for parameter contentScriptOptions (Error processing css.0: Value must either: contain the required "file" property, or .code must be a string value) for contentScripts.register. 2 background.js:395
Type error for parameter contentScriptOptions (Error processing css.0: Value must either: contain the required "file" property, or .code must be a string value) for contentScripts.register. background.js:395
Type error for parameter contentScriptOptions (Error processing css.0: Value must either: contain the required "file" property, or .code must be a string value) for contentScripts.register. background.js:395
Type error for parameter contentScriptOptions (Error processing css.0: Value must either: contain the required "file" property, or .code must be a string value) for contentScripts.register. background.js:395
Type error for parameter contentScriptOptions (Error processing css.0: Value must either: contain the required "file" property, or .code must be a string value) for contentScripts.register. background.js:395
Type error for parameter contentScriptOptions (Error processing css.0: Value must either: contain the required "file" property, or .code must be a string value) for contentScripts.register. background.js:395
NS_ERROR_FAILURE: Failed to open input source 'file:///' DevToolsUtils.js:673
TypeError: Illegal constructor. background.js:1769:29
Security Error: Content at moz-extension://0509c4ae-d72e-4bf3-8039-31da0f19db40/ may not load data from blob:null/ef31a62e-e899-42d5-a8ec-d304f57a3b10.
Security Error: Content at moz-extension://0509c4ae-d72e-4bf3-8039-31da0f19db40/ may not load data from blob:null/889659c8-f340-4026-a8c3-e0994c136d3d.
Security Error: Content at moz-extension://0509c4ae-d72e-4bf3-8039-31da0f19db40/ may not load data from blob:null/14546c9c-be73-4200-badf-f8f4d1ef9f4e.
Type error for parameter contentScriptOptions (Error processing css.0: Value must either: contain the required "file" property, or .code must be a string value) for contentScripts.register. 2 background.js:395
TypeError: Illegal constructor. 2 background.js:1769:29
TypeError: Illegal constructor. background.js:1769:29
NS_ERROR_FAILURE: Failed to open input source 'file:///' DevToolsUtils.js:673

[Exception... "File error: Not found"  nsresult: "0x80520012 (NS_ERROR_FILE_NOT_FOUND)"  location: "JS frame :: jar:file:///C:/Program%20Files/mypal-68.13.7.en-US.win32/mypal/browser/features/webcompat@mozilla.org.xpi!/experiment-apis/pictureInPicture.js :: getPolicies :: line 70"  data: no] pictureInPicture.js:70:11
Error: An unexpected error occurred undefined:14:57
Error: Incorrect argument types for pictureInPictureParent.setOverrides. picture_in_picture_overrides.js:15:36
Error processing colors.toolbar_text: Please use <em>theme.colors.bookmark_text</em>, this alias will be removed in Firefox 69. background.js:2620
TypeError: Illegal constructor. background.js:457:25
TypeError: Argument 1 of PrecompiledScript.executeInGlobal is not an object. 4 ExtensionContent.jsm:552:25
Type error for parameter contentScriptOptions (Error processing css.0: Value must either: contain the required "file" property, or .code must be a string value) for contentScripts.register. background.js:395
TypeError: Illegal constructor. 6 background.js:1769:29
TypeError: details.frameAncestors is undefined
7 background.js:1838:29
TypeError: Illegal constructor. 6 background.js:1769:29
TypeError: Illegal constructor. 19 background.js:1769:29
Type error for parameter contentScriptOptions (Error processing css.0: Value must either: contain the required "file" property, or .code must be a string value) for contentScripts.register. background.js:395
Type error for parameter contentScriptOptions (Error processing css.0: Value must either: contain the required "file" property, or .code must be a string value) for contentScripts.register. background.js:395
Type error for parameter contentScriptOptions (Error processing css.0: Value must either: contain the required "file" property, or .code must be a string value) for contentScripts.register. 2 background.js:395
Type error for parameter contentScriptOptions (Error processing css.0: Value must either: contain the required "file" property, or .code must be a string value) for contentScripts.register. background.js:395
Type error for parameter contentScriptOptions (Error processing css.0: Value must either: contain the required "file" property, or .code must be a string value) for contentScripts.register. background.js:395
TypeError: details.frameAncestors is undefined
2 background.js:1838:29
Type error for parameter contentScriptOptions (Error processing css.0: Value must either: contain the required "file" property, or .code must be a string value) for contentScripts.register. 2 background.js:395
Type error for parameter contentScriptOptions (Error processing css.0: Value must either: contain the required "file" property, or .code must be a string value) for contentScripts.register. background.js:395
Type error for parameter contentScriptOptions (Error processing css.0: Value must either: contain the required "file" property, or .code must be a string value) for contentScripts.register. background.js:395
Type error for parameter contentScriptOptions (Error processing css.0: Value must either: contain the required "file" property, or .code must be a string value) for contentScripts.register. background.js:395
Type error for parameter contentScriptOptions (Error processing css.0: Value must either: contain the required "file" property, or .code must be a string value) for contentScripts.register. background.js:395
Type error for parameter contentScriptOptions (Error processing css.0: Value must either: contain the required "file" property, or .code must be a string value) for contentScripts.register. background.js:395
Type error for parameter contentScriptOptions (Error processing css.0: Value must either: contain the required "file" property, or .code must be a string value) for contentScripts.register. background.js:395
TypeError: details.frameAncestors is undefined
background.js:1838:29
Type error for parameter contentScriptOptions (Error processing css.0: Value must either: contain the required "file" property, or .code must be a string value) for contentScripts.register. background.js:395
TypeError: details.frameAncestors is undefined
background.js:1838:29
Type error for parameter contentScriptOptions (Error processing css.0: Value must either: contain the required "file" property, or .code must be a string value) for contentScripts.register. background.js:395
Type error for parameter contentScriptOptions (Error processing css.0: Value must either: contain the required "file" property, or .code must be a string value) for contentScripts.register. background.js:395
Type error for parameter contentScriptOptions (Error processing css.0: Value must either: contain the required "file" property, or .code must be a string value) for contentScripts.register. 2 background.js:395
Type error for parameter contentScriptOptions (Error processing css.0: Value must either: contain the required "file" property, or .code must be a string value) for contentScripts.register. background.js:395
Type error for parameter contentScriptOptions (Error processing css.0: Value must either: contain the required "file" property, or .code must be a string value) for contentScripts.register. background.js:395
Type error for parameter contentScriptOptions (Error processing css.0: Value must either: contain the required "file" property, or .code must be a string value) for contentScripts.register. background.js:395
Type error for parameter contentScriptOptions (Error processing css.0: Value must either: contain the required "file" property, or .code must be a string value) for contentScripts.register. background.js:395
Type error for parameter contentScriptOptions (Error processing css.0: Value must either: contain the required "file" property, or .code must be a string value) for contentScripts.register. background.js:395
Type error for parameter contentScriptOptions (Error processing css.0: Value must either: contain the required "file" property, or .code must be a string value) for contentScripts.register. background.js:395
Type error for parameter contentScriptOptions (Error processing css.0: Value must either: contain the required "file" property, or .code must be a string value) for contentScripts.register. background.js:395
Type error for parameter contentScriptOptions (Error processing css.0: Value must either: contain the required "file" property, or .code must be a string value) for contentScripts.register. background.js:395
Security Error: Content at moz-extension://0509c4ae-d72e-4bf3-8039-31da0f19db40/ may not load data from blob:null/9dec1056-c568-4b4b-83f6-d29a9af18472.
[Exception... "Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIDOMWindowUtils.removeSheetUsingURIString]"  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: resource://gre/modules/ExtensionCommon.jsm :: runSafeSyncWithoutClone :: line 73"  data: no] ExtensionCommon.jsm:73:12
TypeError: Argument 1 of PrecompiledScript.executeInGlobal is not an object. ExtensionContent.jsm:552:25
Type error for parameter contentScriptOptions (Error processing css.0: Value must either: contain the required "file" property, or .code must be a string value) for contentScripts.register. background.js:395
Type error for parameter contentScriptOptions (Error processing css.0: Value must either: contain the required "file" property, or .code must be a string value) for contentScripts.register. background.js:395
Type error for parameter contentScriptOptions (Error processing css.0: Value must either: contain the required "file" property, or .code must be a string value) for contentScripts.register. 2 background.js:395
Type error for parameter contentScriptOptions (Error processing css.0: Value must either: contain the required "file" property, or .code must be a string value) for contentScripts.register. background.js:395
Type error for parameter contentScriptOptions (Error processing css.0: Value must either: contain the required "file" property, or .code must be a string value) for contentScripts.register. 2 background.js:395
TypeError: can't access dead object
TooltipTextProvider.jsm:15:7
TypeError: details.frameAncestors is undefined
background.js:1838:29
TypeError: Illegal constructor. background.js:1769:29
Security Error: Content at moz-extension://0509c4ae-d72e-4bf3-8039-31da0f19db40/ may not load data from blob:null/4b44dc83-c55a-4924-83b0-3323a3a028d2.
TypeError: Argument 1 of PrecompiledScript.executeInGlobal is not an object. ExtensionContent.jsm:552:25
Type error for parameter contentScriptOptions (Error processing css.0: Value must either: contain the required "file" property, or .code must be a string value) for contentScripts.register. background.js:395
Type error for parameter contentScriptOptions (Error processing css.0: Value must either: contain the required "file" property, or .code must be a string value) for contentScripts.register. background.js:395
Type error for parameter contentScriptOptions (Error processing css.0: Value must either: contain the required "file" property, or .code must be a string value) for contentScripts.register. background.js:395
Type error for parameter contentScriptOptions (Error processing css.0: Value must either: contain the required "file" property, or .code must be a string value) for contentScripts.register. background.js:395
Type error for parameter contentScriptOptions (Error processing css.0: Value must either: contain the required "file" property, or .code must be a string value) for contentScripts.register. background.js:395
Type error for parameter contentScriptOptions (Error processing css.0: Value must either: contain the required "file" property, or .code must be a string value) for contentScripts.register. background.js:395
Type error for parameter contentScriptOptions (Error processing css.0: Value must either: contain the required "file" property, or .code must be a string value) for contentScripts.register. background.js:395
Type error for parameter contentScriptOptions (Error processing css.0: Value must either: contain the required "file" property, or .code must be a string value) for contentScripts.register. background.js:395
Type error for parameter contentScriptOptions (Error processing css.0: Value must either: contain the required "file" property, or .code must be a string value) for contentScripts.register. background.js:395
Type error for parameter contentScriptOptions (Error processing css.0: Value must either: contain the required "file" property, or .code must be a string value) for contentScripts.register. background.js:395
Type error for parameter contentScriptOptions (Error processing css.0: Value must either: contain the required "file" property, or .code must be a string value) for contentScripts.register. background.js:395
Type error for parameter contentScriptOptions (Error processing css.0: Value must either: contain the required "file" property, or .code must be a string value) for contentScripts.register. background.js:395
Type error for parameter contentScriptOptions (Error processing css.0: Value must either: contain the required "file" property, or .code must be a string value) for contentScripts.register. background.js:395
Type error for parameter contentScriptOptions (Error processing css.0: Value must either: contain the required "file" property, or .code must be a string value) for contentScripts.register. background.js:395
Type error for parameter contentScriptOptions (Error processing css.0: Value must either: contain the required "file" property, or .code must be a string value) for contentScripts.register. background.js:395
Type error for parameter contentScriptOptions (Error processing css.0: Value must either: contain the required "file" property, or .code must be a string value) for contentScripts.register. background.js:395
Type error for parameter contentScriptOptions (Error processing css.0: Value must either: contain the required "file" property, or .code must be a string value) for contentScripts.register. 2 background.js:395
Type error for parameter contentScriptOptions (Error processing css.0: Value must either: contain the required "file" property, or .code must be a string value) for contentScripts.register. background.js:395
Type error for parameter contentScriptOptions (Error processing css.0: Value must either: contain the required "file" property, or .code must be a string value) for contentScripts.register. background.js:395
Type error for parameter contentScriptOptions (Error processing css.0: Value must either: contain the required "file" property, or .code must be a string value) for contentScripts.register. background.js:395
Type error for parameter contentScriptOptions (Error processing css.0: Value must either: contain the required "file" property, or .code must be a string value) for contentScripts.register. background.js:395
Type error for parameter contentScriptOptions (Error processing css.0: Value must either: contain the required "file" property, or .code must be a string value) for contentScripts.register. background.js:395
NS_ERROR_FAILURE: Failed to open input source 'file:///' DevToolsUtils.js:673

TypeError: laFonction is undefinedultimadark:902:13
    functionPrototypeEditor https://addons.mozilla.org/en-US/firefox/addon/ultimadark/:902
    functionPrototypeEditor https://addons.mozilla.org/en-US/firefox/addon/ultimadark/:904
    forEach self-hosted:216
    functionPrototypeEditor https://addons.mozilla.org/en-US/firefox/addon/ultimadark/:903
    <anonymous> https://addons.mozilla.org/en-US/firefox/addon/ultimadark/:1103
    <anonymous> https://addons.mozilla.org/en-US/firefox/addon/ultimadark/:1213
    
## Conclusion

It is very angry

**Comment by ThomazPom** [comment]
I'll check this browser, but initially, based on the error message:

TypeError: Illegal constructor. 6 background.js:1769:29

It seems to dislike the line 1769 where a CSSStyleSheet is being constructed:
https://github.com/ThomazPom/Moz-Ext-UltimaDark/blob/20c405f1a291a170366e9c6db508e2eb0c17f8e8/background.js#L1769


While I initially developed UltimaDark without involving CSSStylesheets, using them significantly reduced the number of broken websites, sped up processing by two or three times, and made bug investigations much easier. Reverting to the previous method (parsing strings) only for this browser might not be a viable option.

            
And neither the line 1838 which tries to take advantage of FrameAncestors, as far as i know one of basic features of Firefox
https://github.com/ThomazPom/Moz-Ext-UltimaDark/blob/20c405f1a291a170366e9c6db508e2eb0c17f8e8/background.js#L1838

**Comment by Vintagemotors** [comment]
frameAncestors has been partially broken for 6 years. https://bugzilla.mozilla.org/show_bug.cgi?id=1404438 https://support.mozilla.org/en-US/questions/1297104

**Comment by ThomazPom** [comment]
We are discussing the 'frameAncestors' feature within the webRequest API for extensions. It's important to note that this feature is not  the frame-ancestors directive of the Content Security Policy

**Comment by Vintagemotors** [comment]
I guess I am unable to find the documentation for frameAncestors in that case. Sorry.
