### ISSUE TITLE
Whitelist and Blacklist are currently reversed

### ISSUE THREAD

**Issue by Vintagemotors** [ThomazPom/Moz-Ext-UltimaDark#58]
Sites that require external darkening should be blacklisted - since blacklisted means untrusted, as in we can't trust the site's developer to have implemented dark mode correctly. 

Sites that do not require external darkening should be whitelisted - since whitelisted means they are allowed to function normally.

**Comment by ThomazPom** [comment]
As i have the opposite interpretation of blacklist, (Blacklist website should be excluded from any treatment from UltimaDark), i'm understanding users could understand it in many ways. What about removing this terms (which are anyway too technical )  and keep  only sentences ( or Don't edit these websites
and
Darken these websites

**Comment by Vintagemotors** [comment]
I agree with the decision to remove blacklist and whitelist terms altogether from settings, it just makes it more confusing than needed. 

- Exclude these websites 
- Darken these websites

**Comment by ThomazPom** [comment]
Great, next version will have

    Exclude these websites
    Darken these websites

**Comment by Vintagemotors** [comment]
Has been implemented in 1.5.28
