### ISSUE TITLE
Add Bug Tracker to Projects tab? 

### ISSUE THREAD

**Issue by Vintagemotors** [ThomazPom/Moz-Ext-UltimaDark#59]
You would have to do it. I tried but it has to be hosted on your account. https://github.com/users/Vintagemotors/projects/2

**Comment by ThomazPom** [comment]
Certainly, a great idea! I've done some searching, but I couldn't find clear instructions on how to enable this feature. Is this something that requires creating a new project, or is it a setting of UltimaDark project?

**Comment by CrashBandicoot0001** [comment]
You create a new project on your profile then it will be searchable when you click add project under the projects tab for UltimaDark

**Comment by ThomazPom** [comment]
https://github.com/users/ThomazPom/projects/1

**Comment by Vintagemotors** [comment]
Was added by ThomazPom so closing.
