### ISSUE TITLE
Change the color/style of the Exclude site button

### ISSUE THREAD

**Issue by Vintagemotors** [ThomazPom/Moz-Ext-UltimaDark#60]
I didn't realize until today that it is a button not a status message. If I was confused by it probably someone else will be too. 

Suggested color: Green

**Comment by ThomazPom** [comment]
Will be done in 1.5.29 (yet to be released)

**Comment by ThomazPom** [comment]
https://github.com/ThomazPom/Moz-Ext-UltimaDark/issues/53#issuecomment-1887975555
