### ISSUE TITLE
1.5.37 Image loading regression 

### ISSUE THREAD

**Issue by Vintagemotors** [ThomazPom/Moz-Ext-UltimaDark#73]
SoundCloud images no longer load, this behavior was also observed in the nightly 1.5.37 build. It persists whether or not ImageEdition is enabled.

**Comment by Vintagemotors** [comment]
Same issue on tenor with ImageEdition disabled https://tenor.com/view/%D0%BA%D0%B0%D0%B9%D1%84-%D0%B6%D1%83%D1%82%D0%BA%D0%B8%D0%B9-%D1%81%D0%BC%D0%B5%D1%85-gif-14524534299213067676

**Comment by ThomazPom** [comment]
Thank you for pointing out these cases 👍. I'll investigate them.

**Comment by Vintagemotors** [comment]
1.5.38 is now able to load the images but they are still loading slower than if UltimaDark were disabled, whether or not ImageEdition is enabled.

**Comment by Vintagemotors** [comment]
Resolved in 1.5.40
