### ISSUE TITLE
links in advanced settings

### ISSUE THREAD

**Issue by atomGit** [ThomazPom/Moz-Ext-UltimaDark#74]
the github links in the advanced settings open those pages in the pop-up instead of a tab

also atomGit link should probably be removed

**Comment by Vintagemotors** [comment]
Doesn't open in a popup for me on 1.5.36 or 1.5.37. What Firefox version are you on?

**Comment by Vintagemotors** [comment]
You can edit line 61 and submit a PR if you want to remove yourself https://github.com/ThomazPom/Moz-Ext-UltimaDark/blob/76919acd6f39ff1b75e9b80d68c8b7ac1ab8a792/popup.html#L42 otherwise mention @ ThomazPom

**Comment by atomGit** [comment]
> Doesn't open in a popup for me on 1.5.36 or 1.5.37. What Firefox version are you on?

v122 -- it's a pref then, probably having to do with opening links in the same tab perhaps, however i haven't noticed it in any other add-on links

@ThomazPom - you can remove the atomGit link in advanced settings please

**Comment by ThomazPom** [comment]
Next release will have this link removed.

**Comment by Vintagemotors** [comment]
Completed in 1.5.38
