### ISSUE TITLE
Webpage menu/headings/formatting text misaligns

### ISSUE THREAD

**Issue by audio101** [ThomazPom/Moz-Ext-UltimaDark#80]
Many websites page text menu/heading/spacing/alignment changes & goes all out of whack on some sites when enabled.

**Comment by Vintagemotors** [comment]
While I haven't seen that, I have seen reversions to base html (open issue). Please provide specific examples.

**Comment by Vintagemotors** [comment]
@audio101 Closing in 2 weeks if this is no longer an issue or no examples are provided.

**Comment by ThomazPom** [comment]
This issue is not relevant, since we have a broken sites issue and this bug is too broad and could have been caused by any part of the code including fixed ones in the past 25 days. Closing now
