### ISSUE TITLE
"Image edition" & "UltimaDark" enabled causes many sites not to display/load images or work correctly

### ISSUE THREAD

**Issue by audio101** [ThomazPom/Moz-Ext-UltimaDark#81]
When image edition is enabled, needing an option to be able to exclude certain websites to be able to view images correctly (e.g. Amazon.com, ebay,com). Or otherwise, when image edition is disabled, an option be able to add certain websites on the always allow image edition list.

However, even when image edition is disabled, general browsing with the standard dark mode enabled causes images on many sites not be be able to be viewed or work properly (especially not being able to click on pictures with links), thus having to frequently disable UltimaDark, reload page(s), and/or not have dark mode running.

Hopefully development for the addon to have dark mode enabled & viewable/clickable images & links & with image edition is enabled, always full blacked out background pages loaded, & no sudden 'white flash' bombs. Thanks.

**Comment by Vintagemotors** [comment]
Image edition is still incomplete. the flashing is one of the bugs that appears in some versions of Firefox (and an open issue). It flashes least on Firefox Developer from my experience and worst on 3rd party Firefox releases like Floorp. For clickable links, we haven't seen this. Please provide specific examples.

**Comment by Vintagemotors** [comment]
Closing - previously known issue.
