### ISSUE TITLE
Enable compatibility with Firefox for Android

### ISSUE THREAD

**Issue by csolisr** [ThomazPom/Moz-Ext-UltimaDark#85]
The plugin is reportedly not working properly on Firefox for Android. Please enable it, so it can be used on mobile.

**Comment by Skepller** [comment]
**Not** working properly or working properly?

**Comment by ThomazPom** [comment]
Thanks for bringing up the issue regarding the plugin on Firefox for Android. I don't have an Android device to test it on, so I wasn't aware of any problems. When I uploaded the plugin to the MDN store, did I inadvertently disabled Android support?

**Comment by Vintagemotors** [comment]
It is not compatible due to missing features in Firefox for Android that are required for UltimaDark to function fully, until they are implemented it will remain impractical.

**Comment by ThomazPom** [comment]
@barolo I've activated the Android version of the webext, allowing you to install just as you was used to. @Vintagemotors is perfectly right : While I'm really glad to hear that some of you are finding it to work as well as the desktop version, please understand that I am not actively testing the Android version myself. 

Feel free to use it, but don't be surprised if there are some bugs or if it breaks your user experience.
