### ISSUE TITLE
Broken menu

### ISSUE THREAD

**Issue by chmichael** [ThomazPom/Moz-Ext-UltimaDark#86]
Hello,
  It's breaking the menu on https://zisimopoulos-sa.gr/
  Clicking the menu doesn't popup with UltimaDark enabled.

btw, you should add an button to report broken sites.

Thank you

**Comment by Vintagemotors** [comment]
#6  A report button would be nice but it's quite complicated to implement beyond linking back to Issues given we aren't tracking  anywhere other than GitHub. If you have a suggestion for implementing it that wouldn't require another issue tracker it can be considered. Also please confirm menus still do not work with service worker compatibility and caching off.

**Comment by chmichael** [comment]
AdGuard has it and it opens a public/anonymous ticket to their Github.

**Comment by ThomazPom** [comment]
Thank you for your suggestion.

**Comment by ThomazPom** [comment]
> Hello, It's breaking the menu on https://zisimopoulos-sa.gr/ Clicking the menu doesn't popup with UltimaDark enabled.
> 
> btw, you should add an button to report broken sites.
> 
> Thank you

Fixed in 1.5.52

**Comment by chmichael** [comment]
It is thanks!
