### ISSUE TITLE
Prevents site from loading correctly

### ISSUE THREAD

**Issue by hunkyburrito** [ThomazPom/Moz-Ext-UltimaDark#88]
Trying to access any collection on nexusmods.com ([example collection](https://next.nexusmods.com/witcher3/collections/z5tjm8)) results in the page getting stuck and not displaying anything. The console also gets flooded with messages like below:
![image](https://github.com/user-attachments/assets/846c657e-2b4b-4d77-8ffb-d78b943983d8)

Turning off the extension or excluding the site from the extension fixes it. 

While the site doesn't really need the extension and can just be excluded, I figured I would submit this issue just in case it's a generic problem that could affect other sites.

**Comment by ThomazPom** [comment]
Thank you for reporting this! It looks like a tough issue, and we appreciate you bringing it to our attention.

**Comment by ThomazPom** [comment]
> Trying to access any collection on nexusmods.com ([example collection](https://next.nexusmods.com/witcher3/collections/z5tjm8)) results in the page getting stuck and not displaying anything. The console also gets flooded with messages like below: ![image](https://private-user-images.githubusercontent.com/48025161/363456604-846c657e-2b4b-4d77-8ffb-d78b943983d8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU0OTA4OTYsIm5iZiI6MTcyNTQ5MDU5NiwicGF0aCI6Ii80ODAyNTE2MS8zNjM0NTY2MDQtODQ2YzY1N2UtMmI0Yi00ZDc3LThmZmItZDc4Yjk0Mzk4M2Q4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA0VDIyNTYzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ1MGFkZTBhMDZjOGRmM2Y5ZDg1ZDhkNGViZWY2MjAxZTZlZTJkNjEzMDZhNzlmMzA5NjIxMTUxNzliM2E3NmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WNlv0grI4KYUWXb9Jtm21uHIDab_UXOadMSeL6fWRQU)
> 
> Turning off the extension or excluding the site from the extension fixes it.
> 
> While the site doesn't really need the extension and can just be excluded, I figured I would submit this issue just in case it's a generic problem that could affect other sites.


Fixed in 1.5.52

**Comment by ThomazPom** [comment]
Fixed in 15.5.53. Was a tough one
