### ISSUE TITLE
Auto enable/disable based on if dark mode is enabled in browser/os

### ISSUE THREAD

**Issue by oktayacikalin** [ThomazPom/Moz-Ext-UltimaDark#89]
Thank you for your effort - this works great so far!

But, as I'm using my OS in light mode during the day, I would really love to see that this extension would pick this setting up and enable itself only if my OS/browser is using the dark mode UI. And disable itself when I swtich back to light mode UI.

**Comment by Vintagemotors** [comment]
Moved to feature requests.
