### ISSUE TITLE
UltimaDark disables Proton Pass features

### ISSUE THREAD

**Issue by Aiakio** [ThomazPom/Moz-Ext-UltimaDark#90]
If UltimaDark is enabled, Proton Pass's autofill features are not working anymore. Always have to copy and paste the login credentials manually. With that, also Passkey login is not working anymore.

As soon as i disable UltimaDark, everything in Proton Pass works again.

**Comment by ThomazPom** [comment]
Is the issue still present in 1.5.53 ?

**Comment by Max-109** [comment]
Hi, i also experience this issues. I'm on the latest version of Ultimadark (1.6.6) and on the latest version of proton pass

**Comment by ThomazPom** [comment]
Release v1.6.11
Resolved compatibility issues with other applications, including ProtonPass, by removing the coliding redefinition of shared `globalThis.exportFunction`  and having our own `uDark.exportFunction `definition.

https://github.com/ThomazPom/Moz-Ext-UltimaDark/releases/tag/v1.6.11

https://github.com/ThomazPom/Moz-Ext-UltimaDark/commit/0d040896b65a5b6e76c2b3057e6b44ae2f56febb#diff-673e98e9518fe407b7538bc62ef555f6eb5290996f4ea87b66783700af9a8a03R6
