### ISSUE TITLE
Enable Android Support

### ISSUE THREAD

**Issue by anatasiajp** [ThomazPom/Moz-Ext-UltimaDark#93]
Currently UltimaDark works great on Android, but it's not installable without changing to Desktop Mode in AMO.

Android needs Dark Mode support more considering phone is slower than pc, please enabled mobile on AMO.

**Comment by ThomazPom** [comment]
Thank you for your feedback.

Support is enabled in AMO 
![image](https://github.com/user-attachments/assets/b64386af-255d-4f28-81e4-8e88d716ac41)

Please read this ;
https://github.com/ThomazPom/Moz-Ext-UltimaDark/issues/85#issuecomment-2332545282

**Comment by anatasiajp** [comment]
Thank you, I've recently stumbled upon this lemmy thread and I've found a lot of users asking for Android support: https://lemmy.ml/post/19695232

UltimaDark is getting a lot of attention lately I feel like, truly deserved!
