### ISSUE TITLE
Economist.com & bpc too dark

### ISSUE THREAD

**Issue by fredgolightly** [ThomazPom/Moz-Ext-UltimaDark#95]
I'm finding using the latest version on firefox Android stable with bypass paywalls clean to pull full text it loads fine, but once full text is inserted it's too dark, with over bright mid sections like https://i.postimg.cc/yNTtc6Yv/Screenshot-20240913-204122-Firefox.png

**Comment by Vintagemotors** [comment]
Firefox for Android is unsupported, installation is enabled as highly experimental for testing purposes only. Firefox for Android is missing core features that UltimaDark relies on to function properly. Please only post issues that are confirmed on desktop. In Economist.com's case on desktop the "One month free trial" text is too dark and everything else is readable.
