### ISSUE TITLE
Automatic on/off based on location (or time or theme)

### ISSUE THREAD

**Issue by dd871** [ThomazPom/Moz-Ext-UltimaDark#96]
I was using other extensions in the past but always ran into issues and little annoyances that eventually became a showstopper.

Found this extension by searching for alternatives and really love it as it is so quick and surprisingly just works on most of the sites I visit.

One big drawback though is that I have to manually enable it in the evening and then disable it again the next morning. All off my other theme (light/dark) settings in my system I was able to automate (mostly by using "Auto Dark Mode" for Windows - a great little tool).

Would it be possible to implement a simple way to automate this also for UltimaDark? Ideal case would be based on sunset of location but even the most simple one based just on time would already be a great improvement.

Alternatively - is there a way to somehow trigger the extension status via Powershell or something like that?

**Comment by Vintagemotors** [comment]
@dd871 Closing duplicate https://github.com/ThomazPom/Moz-Ext-UltimaDark/issues/19#issuecomment-2325279311
