### ISSUE TITLE
v1.5.63 introduced a new css flow issue

### ISSUE THREAD

**Issue by atomGit** [ThomazPom/Moz-Ext-UltimaDark#97]
url: `https://forecast.weather.gov/MapClick.php?CityName=Atlanta+Junction&state=GA&site=FFC&textField1=34.2139&textField2=-85.1828`

UD off...
![ud-off--weather gov](https://github.com/user-attachments/assets/5901dbe8-85b8-4b63-ac51-1ae4d91c2fe5)

UD on...
![ud-on--weather gov](https://github.com/user-attachments/assets/c7107782-7fe3-4205-85e5-500adce14f8c)

**Comment by ThomazPom** [comment]
Will be fixed in 1.5.65; Thank you !!!

**Comment by ThomazPom** [comment]
1.5.65 released on AMO

**Comment by atomGit** [comment]
much better - thanks Thomaz!
